// <auto-generated />
using MasGLobal.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MasGlobal.Model.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200217194225_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MasGLobal.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("salary");

                    b.Property<int>("salaryId");

                    b.HasKey("Id");

                    b.HasIndex("salaryId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mark",
                            salary = 1,
                            salaryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Stephan",
                            salary = 1000,
                            salaryId = 2
                        });
                });

            modelBuilder.Entity("MasGlobal.Model.SalaryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("SalaryType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hourly Salary"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Montly Salary"
                        });
                });

            modelBuilder.Entity("MasGLobal.Model.Employee", b =>
                {
                    b.HasOne("MasGlobal.Model.SalaryType", "SalaryType")
                        .WithMany("Employee")
                        .HasForeignKey("salaryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
